server:
  port: 9090

spring:
  application:
    name: securebank

  datasource:
    url: jdbc:postgresql://localhost:5432/securebank
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  secretKey: ${JWT_SECRET}
  expirationMs: 900000


